params:
  seed: 42
  algo: {name: a2c_discrete}
  model: {name: discrete_a2c}
  network:
    name: actor_critic
    separate: false
    space: {discrete: null}
    cnn:
      type: conv2d
      activation: elu
      initializer: {name: orthogonal_initializer, gain: 1.41421356237}
      convs:
      - {filters: 32, kernel_size: 8, strides: 4, padding: 0}
      - {filters: 64, kernel_size: 4, strides: 2, padding: 0}
      - {filters: 64, kernel_size: 3, strides: 1, padding: 0}
    mlp:
      units: [512]
      activation: elu
      initializer: {name: orthogonal_initializer, gain: 1.41421356237}
  config:
    name: Mario_Native84
    env_name: mario_native
    score_to_win: 100000
    normalize_value: true
    normalize_input: false
    reward_shaper: {scale_value: 1.0}
    normalize_advantage: true
    gamma: 0.995
    tau: 0.95
    learning_rate: 0.00025
    lr_schedule: adaptive
    kl_threshold: 0.008
    grad_norm: 0.5
    entropy_coef: 0.02
    truncate_grads: true
    e_clip: 0.1
    clip_value: true
    num_actors: 128
    horizon_length: 128
    minibatch_size: 4096
    mini_epochs: 4
    critic_coef: 0.5
    max_epochs: 4000
    use_diagnostics: true
    save_frequency: 500
    save_best_after: 500
    print_stats: true
    device: cuda:0
    multi_gpu: false
    stage_curriculum_freq: 0
    env_config:
      name: SuperMarioBros-v0
      action_type: complex
      episode_life: true
      x_reward: highwater
      loop_penalty: 30
      backtrack_penalty: 0.15
      novelty_bonus: 3.0
      full_game: true
      stage_bonus: 500
      idle_penalty: 0.5
      idle_threshold: 10
      progress_reward: 0.001
      skip: 4
      sticky_actions: 0.1
      reset_noops: 30
      random_stages: [8-4]
      self_restart_prob: 0.3
      n_threads: 16
      self_restart_cells: 128
      novelty_y_band: 24
      score_reward: 0.1
      novelty_global: true
    player: {render: false, games_num: 10, deterministic: true, n_game_life: 3}
    eval_env_config:
      backend: native
      random_stages: [8-4]
      full_game: true
      x_reward: highwater
